using System;
using System.Web.Http;
using System.Web.Http.Description;
using TrackMyGradeAPI.Handlers;
using TrackMyGradeAPI.Logging;

namespace TrackMyGradeAPI.Controllers
{
    /// <summary>
    /// Test controller for ELMAH error logging verification.
    /// Provides endpoints to trigger and verify error logging without affecting production data.
    /// </summary>
    [RoutePrefix("api/test")]
    public class TestController : ApiController
    {
        /// <summary>
        /// Test endpoint that throws an exception to verify ELMAH error logging is working.
        /// This should be removed or restricted to development environments in production.
        /// </summary>
        [HttpGet, Route("throw-error")]
        [ResponseType(typeof(object))]
        public IHttpActionResult ThrowError()
        {
            try
            {
                // Simulate a database access error
                throw new System.InvalidOperationException(
                    "This is a test exception generated by the /api/test/throw-error endpoint. " +
                    "ELMAH should have logged this error. Check the ELMAH error log to verify.");
            }
            catch (Exception ex)
            {
                ErrorLoggingConfig.LogErrorWithMessage(
                    "TEST: Intentional error to verify ELMAH logging",
                    ex);
                return InternalServerError(ex);
            }
        }

        /// <summary>
        /// Test endpoint that throws an exception with additional context.
        /// Verifies that contextual information is properly captured by ELMAH.
        /// </summary>
        [HttpGet, Route("throw-error-with-context")]
        [ResponseType(typeof(object))]
        public IHttpActionResult ThrowErrorWithContext()
        {
            try
            {
                // Simulate a validation error
                throw new ArgumentException("Invalid input value provided for test");
            }
            catch (Exception ex)
            {
                string userId = Request.GetUserId().ToString();
                string requestUri = Request.RequestUri?.ToString() ?? "unknown";
                string method = Request.Method.ToString();

                ErrorLoggingConfig.LogErrorWithFullContext(
                    ex,
                    userId,
                    requestUri,
                    method,
                    Request.Content?.Headers?.ContentType?.ToString(),
                    new System.Collections.Generic.Dictionary<string, object>
                    {
                        { "TestEndpoint", "throw-error-with-context" },
                        { "TestPurpose", "Verify context logging" }
                    });

                return InternalServerError(ex);
            }
        }

        /// <summary>
        /// Test endpoint that simulates a data integrity error.
        /// Verifies that data consistency errors are properly logged with entity context.
        /// </summary>
        [HttpGet, Route("throw-data-integrity-error")]
        [ResponseType(typeof(object))]
        public IHttpActionResult ThrowDataIntegrityError()
        {
            try
            {
                throw new System.Data.DBConcurrencyException(
                    "Concurrency conflict: Entity has been modified by another user");
            }
            catch (Exception ex)
            {
                ErrorLoggingConfig.LogDataIntegrityError(
                    ex,
                    "UPDATE",
                    "Student",
                    123);

                return InternalServerError(ex);
            }
        }

        /// <summary>
        /// Test endpoint that returns a successful health check.
        /// Verifies that the API is running and ELMAH is accessible.
        /// </summary>
        [HttpGet, Route("health")]
        [ResponseType(typeof(object))]
        public IHttpActionResult HealthCheck()
        {
            return Ok(new
            {
                status = "healthy",
                timestamp = DateTime.UtcNow,
                message = "TrackMyGrade API is running. ELMAH error logging is enabled."
            });
        }
    }
}
