using Swashbuckle.Application;
using System;
using System.IO;
using System.Web.Http;

namespace TrackMyGradeAPI.Infrastructure
{
    public static class SwaggerConfig
    {
        public static void Register(HttpConfiguration config)
        {
            config
                .EnableSwagger(c =>
                {
                    c.SingleApiVersion("v1", "TrackMyGrade API")
                        .Description("REST API for managing student grades and teacher assessments.")
                        .Contact(cc => cc.Name("TrackMyGrade Team"));

                    // Required for OWIN self-hosting: derive the base URL from the request
                    // instead of relying on HttpContext which is always null in self-hosted OWIN.
                    c.RootUrl(req => req.RequestUri.GetLeftPart(UriPartial.Authority));

                    // Load XML doc comments generated by the compiler (csproj DocumentationFile)
                    var xmlPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "TrackMyGradeAPI.XML");
                    if (File.Exists(xmlPath))
                        c.IncludeXmlComments(xmlPath);

                    // Render enums as their string names in the UI
                    c.DescribeAllEnumsAsStrings();
                })
                .EnableSwaggerUi(ui =>
                {
                    ui.DocumentTitle("TrackMyGrade API - Swagger UI");
                });
        }
    }
}
